#define SETPLYBASE	0
#define SETPLYERR	1

#define SETSRTBASE	0
#define SETSRTNULL	1
#define SETSRTERR	2

#define GENSHRBASE	0
#define GENSHRPLY	1
#define GENSHRSRT	2
#define GENSHRERR	3

#define RECONSTRBASE	0
#define RECONSTRLABEL	1
#define RECONSTRELIMAT	2